"""CAN message logging module.

Handles logging of CAN messages to CSV and TRC files.
"""

import csv
import logging
import os
import re
import threading
import time
from collections import deque
from datetime import datetime
from typing import Optional

import can

logger = logging.getLogger(__name__)


class CANLogger:
    """Manages CAN message logging to CSV and TRC files."""

    def __init__(self):
        """Initialize CAN logger."""
        self.logging = False
        self.csv_file: Optional[object] = None
        self.csv_writer: Optional[csv.writer] = None
        self.trc_file: Optional[object] = None
        self.start_time: Optional[datetime] = None
        self.message_counter = 0
        self.first_msg_time: Optional[float] = None
        self.log_lock = threading.Lock()
        self.message_history = deque(maxlen=10000)
        self.message_history_lock = threading.Lock()

    def start_logging(self, filename_base: str) -> str:
        """Start logging CAN messages to CSV and TRC files.

        Args:
            filename_base: Base filename (without extension) for log files.
                          Must be a valid filename without path separators.

        Returns:
            Full path to the log files (without extension).

        Raises:
            ValueError: If filename_base contains invalid characters.
            OSError: If the results directory cannot be created or files cannot be opened.
        """
        # Validate filename to prevent path traversal
        if not filename_base or '..' in filename_base or os.path.sep in filename_base:
            raise ValueError(f"Invalid filename_base: {filename_base}")

        # Sanitize filename - only allow alphanumeric, underscore, hyphen, and dot
        if not re.match(r'^[\w\-\.]+$', filename_base):
            raise ValueError(f"Filename contains invalid characters: {filename_base}")

        # Create Test Results folder if it doesn't exist
        results_dir = "Test Results"
        os.makedirs(results_dir, exist_ok=True)

        # Full path with Test Results folder
        full_path = os.path.join(results_dir, filename_base)

        self.logging = True
        self.start_time = datetime.now()  # Record start time for TRC

        # CSV file
        self.csv_file = open(f"{full_path}.csv", 'w', newline='', encoding='utf-8')
        self.csv_writer = csv.writer(self.csv_file)
        self.csv_writer.writerow(["Time", "Type", "ID", "DLC", "Data"])

        # TRC file (PCAN format)
        self.trc_file = open(f"{full_path}.trc", 'w', encoding='utf-8')
        self._write_trc_header()

        logger.info(f"Started logging to {full_path}")
        return full_path

    def stop_logging(self) -> None:
        """Stop logging and safely close all log files."""
        self.logging = False
        errors = []

        if self.csv_file:
            try:
                self.csv_file.close()
            except Exception as e:
                errors.append(f"CSV close failed: {e}")
                logger.error(f"CSV close failed: {e}")
            finally:
                self.csv_file = None
                self.csv_writer = None

        if self.trc_file:
            try:
                self.trc_file.close()
            except Exception as e:
                errors.append(f"TRC close failed: {e}")
                logger.error(f"TRC close failed: {e}")
            finally:
                self.trc_file = None

        if errors:
            logger.warning(f"Errors stopping logging: {'; '.join(errors)}")
        else:
            logger.info("Logging stopped")

    def _write_trc_header(self) -> None:
        """Write TRC file header in PCAN format."""
        start_time_str = self.start_time.strftime("%d-%m-%Y %H:%M:%S.%f")[:-3]
        # PCAN-style STARTTIME uses Excel/PCAN serial days (days since 1899-12-30)
        excel_epoch = datetime(1899, 12, 30)
        start_serial = (self.start_time - excel_epoch).total_seconds() / 86400.0

        with self.log_lock:
            self.trc_file.write(";$FILEVERSION=1.1\n")
            self.trc_file.write(f";$STARTTIME={start_serial:.10f}\n")
            self.trc_file.write(";\n")
            self.trc_file.write(f";   Start time: {start_time_str}\n")
            self.trc_file.write(";   Generated by AtomX\n")
            self.trc_file.write(";\n")
            self.trc_file.write(";   Message Number\n")
            self.trc_file.write(";   |         Time Offset (ms)\n")
            self.trc_file.write(";   |         |        Type\n")
            self.trc_file.write(";   |         |        |        ID (hex)\n")
            self.trc_file.write(";   |         |        |        |     Data Length\n")
            self.trc_file.write(";   |         |        |        |     |   Data Bytes (hex) ...\n")
            self.trc_file.write(";   |         |        |        |     |   |\n")
            self.trc_file.write(";---+--   ----+----  --+--  ----+---  +  -+ -- -- -- -- -- -- --\n")
            self.message_counter = 1
            self.first_msg_time = None

    def log_message(self, msg: can.Message) -> None:
        """Log CAN message to CSV and TRC files.

        Args:
            msg: CAN message to log
        """
        if not self.logging:
            return

        # Skip CAN error/status frames or remote frames
        try:
            if getattr(msg, "is_error_frame", False) or getattr(msg, "is_remote_frame", False):
                return
        except Exception:
            pass

        # Require a valid arbitration ID
        if not hasattr(msg, "arbitration_id") or msg.arbitration_id is None:
            return
        if not isinstance(msg.arbitration_id, int):
            return

        # Serialize logging to keep message numbers and timestamps monotonic
        with self.log_lock:
            # Use monotonic clock for stable offsets
            now_mono = time.monotonic()
            if self.first_msg_time is None:
                self.first_msg_time = now_mono
            relative_time = max(0.0, (now_mono - self.first_msg_time) * 1000)  # milliseconds

            dlc = getattr(msg, "dlc", len(msg.data) if hasattr(msg, "data") else 0)
            if dlc is None:
                dlc = 0
            dlc = max(0, min(int(dlc), 8))

            data_bytes = ""
            if hasattr(msg, "data") and msg.data is not None:
                data_bytes = ' '.join([f'{b:02X}' for b in list(msg.data)[:dlc]])

            # CSV format
            if self.csv_writer:
                msg_type = "Rx" if getattr(msg, "is_rx", False) else "Tx"
                self.csv_writer.writerow([
                    f"{relative_time:.3f}",
                    msg_type,
                    f"{msg.arbitration_id:03X}",
                    dlc,
                    data_bytes
                ])
                if self.csv_file:
                    self.csv_file.flush()

            # TRC format
            if self.trc_file:
                msg_type = "Rx" if getattr(msg, "is_rx", False) else "Tx"
                trc_line = f"{self.message_counter:6d}){relative_time:11.1f}  {msg_type:2s} {msg.arbitration_id:9X}  {dlc:1d}  {data_bytes} \n"
                self.trc_file.write(trc_line)
                self.trc_file.flush()
                self.message_counter += 1

        # Add to message history for debugging (thread-safe with deque)
        with self.message_history_lock:
            self.message_history.append({
                'timestamp': getattr(msg, "timestamp", None),
                'msg_id': msg.arbitration_id,
                'data': getattr(msg, "data", b''),
                'direction': 'RX' if getattr(msg, "is_rx", False) else 'TX'
            })

    def get_message_history(self) -> list:
        """Get recent message history.

        Returns:
            List of recent messages
        """
        with self.message_history_lock:
            return list(self.message_history)
