"""Unit tests for CAN logging module."""

import os
from unittest.mock import Mock
import pytest
import can

from core.can.logging import CANLogger


@pytest.mark.unit
class TestCANLogger:
    """Test suite for CANLogger class."""

    def test_init(self):
        """Test CANLogger initialization."""
        logger = CANLogger()

        assert not logger.logging
        assert logger.csv_file is None
        assert logger.trc_file is None
        assert logger.message_counter == 0

    def test_start_logging(self, temp_test_dir):
        """Test starting CAN message logging."""
        logger = CANLogger()

        # Change to temp directory
        os.chdir(temp_test_dir)

        full_path = logger.start_logging("test_log")

        assert logger.logging
        assert logger.csv_file is not None
        assert logger.trc_file is not None
        assert logger.start_time is not None
        assert "Test Results" in full_path

        logger.stop_logging()

    def test_start_logging_invalid_filename(self):
        """Test starting logging with invalid filename."""
        logger = CANLogger()

        # Test path traversal
        with pytest.raises(ValueError):
            logger.start_logging("../evil_path")

        # Test invalid characters
        with pytest.raises(ValueError):
            logger.start_logging("test|file<>name")

    def test_stop_logging(self, temp_test_dir):
        """Test stopping CAN message logging."""
        logger = CANLogger()
        os.chdir(temp_test_dir)

        logger.start_logging("test_log")
        logger.stop_logging()

        assert not logger.logging
        assert logger.csv_file is None
        assert logger.trc_file is None

    def test_log_message(self, temp_test_dir):
        """Test logging a CAN message."""
        logger = CANLogger()
        os.chdir(temp_test_dir)

        logger.start_logging("test_log")

        # Create test message
        msg = can.Message(
            arbitration_id=0x123,
            data=[0x01, 0x02, 0x03],
            is_rx=True
        )

        logger.log_message(msg)

        # Verify message was logged
        assert logger.message_counter > 0

        logger.stop_logging()

    def test_log_message_when_not_logging(self):
        """Test logging message when logging is disabled."""
        logger = CANLogger()

        msg = can.Message(
            arbitration_id=0x123,
            data=[0x01, 0x02, 0x03]
        )

        # Should not raise exception
        logger.log_message(msg)
        assert logger.message_counter == 0

    def test_log_error_frame(self, temp_test_dir):
        """Test that error frames are not logged."""
        logger = CANLogger()
        os.chdir(temp_test_dir)

        logger.start_logging("test_log")

        # Counter starts at 1 from header initialization
        initial_counter = logger.message_counter

        # Create error frame
        msg = can.Message(
            arbitration_id=0x123,
            data=[0x01],
            is_error_frame=True
        )

        logger.log_message(msg)

        # Error frames should not increment counter
        assert logger.message_counter == initial_counter

        logger.stop_logging()

    def test_message_history(self, temp_test_dir):
        """Test message history tracking."""
        logger = CANLogger()
        os.chdir(temp_test_dir)

        logger.start_logging("test_log")

        # Log some messages
        for i in range(5):
            msg = can.Message(
                arbitration_id=0x100 + i,
                data=[i],
                is_rx=True
            )
            logger.log_message(msg)

        history = logger.get_message_history()
        assert len(history) == 5
        assert history[0]['msg_id'] == 0x100
        assert history[4]['msg_id'] == 0x104

        logger.stop_logging()

    def test_trc_header_format(self, temp_test_dir):
        """Test TRC file header formatting."""
        logger = CANLogger()
        os.chdir(temp_test_dir)

        logger.start_logging("test_log")
        logger.stop_logging()

        # Read TRC file
        trc_path = os.path.join("Test Results", "test_log.trc")
        with open(trc_path, 'r') as f:
            content = f.read()

        assert ";$FILEVERSION=1.1" in content
        assert ";$STARTTIME=" in content
        assert "Generated by AtomX" in content
